### ISSUE TITLE
Slight rename for project/repo?

### ISSUE THREAD

**Issue by wibeasley** [aarenson/PHPCap#3]
@aarenson, consider renaming your project/repository so it's more distinctive. As it's currently named, it potentially collides with three other projects ([redcapAPI](https://github.com/nutterb/redcapAPI) written in R, [RedcapAPI](https://github.com/eugyev/RedcapAPI) written in Ruby, [REDCap_API](https://github.com/james2012/REDCap_API) written in JavaScript).

I started to add your library to an informal list on [REDCapR's README file](https://github.com/OuhscBbmc/REDCapR), and realized that space looks pretty crowded already:

![image](https://cloud.githubusercontent.com/assets/1372890/8466411/0ed0c442-2018-11e5-896d-da5888f996ea.png)

And even though you have different capitalization, apparently GitHub doesn't like the collision, because it renamed my fork of your repo to [redcapapi-1](https://github.com/wibeasley/redcapapi-1), presumably because it collides with my fork of @nutterb's [redcapAPI](https://github.com/wibeasley/redcapAPI).

If you rename the repo, GitHub automatically will redirect people to the repo's new url.  Which is nice that you don't have to go back and find & change all the old links in things like message boards.

**Comment by aarenson** [comment]
Thanks, Will, both for the idea and the info about how renaming works. I agree a better name would be better. What do you think of REDCapAPIphp?

**Comment by wibeasley** [comment]
If you do something like `REDCapAPIphp`, I'd prefer `REDCapApiPhp`, `redcap_api_php` or `redcap-api-php`.  But I know everyone has different capitalization schemes,

I intentionally excluded "API" from the name of `REDCapR` in case Rob started offering a second way to interact with the server.  But a name like `REDCapPhp` would be confusing since REDCap is written in PHP.  

I wanted "REDCap" explicitly in the name, because I think it helps Google to find.  But that may be unnecessary, because Scott Burns's [PyCap](https://github.com/sburns/PyCap) did well in the search results when he was actively developing it.  It still is, actually.

**Comment by aarenson** [comment]
Great comments.

PhpCap ?

Not perfect, but at least it's short.

**Comment by wibeasley** [comment]
"PhpCap" makes sense to me.  Either way, I'd include links to http://www.project-redcap.org/ in several places in your README so it's easier for AltaVista to make the connection between your package and REDCap.

Before you do that, I suggest either accepting or rejecting my 2nd pull request (ie https://github.com/aarenson/redcapapi/pull/2).  Otherwise, it will take extra work to resolve conflicts if you later merge those modifications.

**Comment by aarenson** [comment]
Thanks, thanks, and thanks. Thought I'd merged that 2nd pull request already!

Umm ... AltaVista? Did I just fall back in time 20 years?

**Comment by wibeasley** [comment]
@aarenson changed the name with the following commits
- acb44e016e2dbe4175ec898e97f3cc1953ba72ea
- 81a5925cb05dc82d5c747b4da9dcb163e7862942
